name: Build Infrastructure

on:
  workflow_dispatch:
  #push:
    #branches:
      #- testing_azroles

env:
  TF_LOG: INFO
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

permissions:
      id-token: write
      contents: read
jobs: 
  Terraform-Init-Validate-Plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # Log into Azure with OIDC integration
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    # Run Terraform init
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"     
    
    #Run Validate  
    - name: Terraform Validate
      id: validate
      run: terraform validate 

    #Run TF plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan.out

    #Upload the TF Provider lock file
    - name: Upload TF Provider Lock File
      uses: actions/upload-artifact@v4
      with:
        name: terraform-lock
        path: .terraform.lock.hcl
        include-hidden-files: true
        if-no-files-found: error

    #Upload the TF init Artifact
    - name: Upload TF init Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-init
        path: .terraform
        include-hidden-files: true
        if-no-files-found: error

    #Upload the TF plan
    - name: Upload TF Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan.out


  Terraform-apply:
    name: Terraform Apply
    needs: Prepare-Terraform-Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment:
      name: production
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Log into Azure with OIDC integration
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Download the tfplan from apply
    - name: Download TF Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: .

    # Download the provider lock file from apply job
    - name: Download TF Provider Lock File
      uses: actions/download-artifact@v4
      with:
        name: terraform-lock
        path: .

    # Download the provider lock file from apply job
    - name: Download TF init Artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-init
        path: ./.terraform        
  
    #Change permissions on artifacts    
    - name: Change Permissions on Downloaded Artifacts
      run: |
        echo "Updating file permissions for downloaded files in $PWD"
        chmod -R 755 $PWD/.terraform
        chmod -R 755 $PWD/tfplan.out
        chmod -R 755 $PWD/.terraform.lock.hcl

      #Run Terraform Apply
    - name: Terraform Apply
      id: apply
      run: terraform apply tfplan.out


    #- name: Terraform Destroy
     # id: destroy
      #run: |
       #  terraform plan -input=false -destroy \
        # -out "tfplan-destroy.out"
         #terraform apply -destroy -input=false -auto-approve tfplan-destroy.out