name: Push

on:
  workflow_dispatch:
  #push:
    #branches:
      #- testing_azroles

env:
  TF_LOG: INFO
  #WORK_DIRECTORY: './' # Set Working Directory To Deployment Type Being Provisioned

permissions:
      id-token: write
      contents: read
jobs: 
  Prepare-Terraform-Plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }} # Set Terraform Working Directory
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # Log into Azure with OIDC integration
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Run az commands to confirm sub access
    - name: 'Run az commands'
      run: |
        az account show

    # Run Terraform init
    - name: Terraform Init
      id: init
      env:
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"

    - name: Show working directory
      run: pwd
    
    - name: Show GitHub workspace
      run: echo "${{ github.workspace }}"

    - name: List files
      run: ls -la
    
    - name: Upload lock file
      uses: actions/upload-artifact@v4
      with:
        name: terraform-lock
        path: terraform/terraform/**/.terraform.lock.hcl
    
    - name: Show GitHub workspace
      run: echo "${{ github.workspace }}"

    - name: Show working directory
      run: pwd

    - name: Terraform Plan
      env:
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform plan -out=tfplan.out
    
    - name: Upload tfplan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan.out


  Terraform-apply:
    name: Terraform Apply
    needs: Prepare-Terraform-Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORK_DIRECTORY }} # Set Terraform Working Directory
    environment:
      name: production
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    # Download the tfplan from apply
    - name: Download tfplan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: .
    # Download the provider lock file from apply job
    - name: Download lock file
      uses: actions/download-artifact@v4
      with:
        name: terraform-lock
        path: .
    - name: Terraform Apply
      id: apply
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform apply tfplan.out